<#
.SYNOPSIS
    Codebase exploration script for bootstrapping GitHub Copilot agents.
    Outputs a Markdown-formatted report of project structure, dependencies,
    database providers, frontend signals, and code conventions.

.DESCRIPTION
    Run from the repository root. Produces a structured Markdown report to stdout
    that both AI agents and humans can read without further processing.

.EXAMPLE
    cd C:\path\to\repo
    .\eng\explore-codebase.ps1
    .\eng\explore-codebase.ps1 | Out-File -FilePath exploration-report.md -Encoding utf8
#>

param(
    [string]$Root = (Get-Location).Path
)

$ErrorActionPreference = 'SilentlyContinue'

# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────
function Rel([string]$FullPath) { $FullPath.Replace($Root, '.').Replace('\', '/') }
function Excluded { param([string]$Path) $Path -match '[\\/](bin|obj|node_modules|\.git|\.vs|packages|TestResults|\.idea)[\\/]' }

Write-Output "# Codebase Exploration Report"
Write-Output ""
Write-Output "> Auto-generated by ``explore-codebase.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Output "> Root: ``$Root``"
Write-Output ""

# ═════════════════════════════════════════════
# 1. Solution & Project Structure
# ═════════════════════════════════════════════
Write-Output "## 1. Solution & Project Files"
Write-Output ""

$slnFiles = Get-ChildItem -Path $Root -Filter "*.sln" -Recurse -File | Where-Object { -not (Excluded $_.FullName) }
if ($slnFiles) {
    Write-Output "### Solution Files"
    Write-Output ""
    foreach ($sln in $slnFiles) { Write-Output "- ``$(Rel $sln.FullName)``" }
    Write-Output ""
}

$csprojFiles = Get-ChildItem -Path $Root -Filter "*.csproj" -Recurse -File | Where-Object { -not (Excluded $_.FullName) }

if ($csprojFiles) {
    Write-Output "### Projects"
    Write-Output ""

    foreach ($csproj in $csprojFiles) {
        $relativePath = Rel $csproj.FullName
        [xml]$xml = Get-Content $csproj.FullName -Raw

        $tf = $xml.Project.PropertyGroup.TargetFramework | Where-Object { $_ } | Select-Object -First 1
        $tfs = $xml.Project.PropertyGroup.TargetFrameworks | Where-Object { $_ } | Select-Object -First 1
        $framework = if ($tf) { $tf } elseif ($tfs) { $tfs } else { "?" }
        $nullable = $xml.Project.PropertyGroup.Nullable | Where-Object { $_ } | Select-Object -First 1
        $outputType = $xml.Project.PropertyGroup.OutputType | Where-Object { $_ } | Select-Object -First 1

        Write-Output "#### ``$relativePath``"
        Write-Output ""

        $meta = @("**Framework**: ``$framework``")
        if ($outputType) { $meta += "**Output**: ``$outputType``" }
        if ($nullable)   { $meta += "**Nullable**: ``$nullable``" }
        Write-Output ($meta -join ' | ')
        Write-Output ""

        # Package references
        $pkgRefs = $xml.Project.ItemGroup.PackageReference | Where-Object { $_.Include }
        if ($pkgRefs) {
            Write-Output "| Package | Version |"
            Write-Output "|---|---|"
            foreach ($pkg in $pkgRefs) {
                $ver = if ($pkg.Version) { $pkg.Version } else { "—" }
                Write-Output "| ``$($pkg.Include)`` | $ver |"
            }
            Write-Output ""
        }

        # Project references
        $projRefs = $xml.Project.ItemGroup.ProjectReference | Where-Object { $_.Include }
        if ($projRefs) {
            Write-Output "**Project References**:"
            foreach ($ref in $projRefs) { Write-Output "- ``$($ref.Include)``" }
            Write-Output ""
        }
    }
}

# ═════════════════════════════════════════════
# 2. Database Detection
# ═════════════════════════════════════════════
Write-Output "## 2. Database & Data Access"
Write-Output ""

$dbPackagePatterns = @{
    'SQL Server'       = 'Microsoft\.EntityFrameworkCore\.SqlServer|System\.Data\.SqlClient|Microsoft\.Data\.SqlClient'
    'Azure SQL'        = 'Microsoft\.EntityFrameworkCore\.SqlServer|Microsoft\.Azure\.Services\.AppAuthentication'
    'PostgreSQL'       = 'Npgsql|Npgsql\.EntityFrameworkCore\.PostgreSQL'
    'MySQL'            = 'MySql\.EntityFrameworkCore|Pomelo\.EntityFrameworkCore\.MySql|MySql\.Data|MySqlConnector'
    'MariaDB'          = 'Pomelo\.EntityFrameworkCore\.MySql|MySqlConnector'
    'SQLite'           = 'Microsoft\.EntityFrameworkCore\.Sqlite|System\.Data\.SQLite|Microsoft\.Data\.Sqlite'
    'Oracle'           = 'Oracle\.EntityFrameworkCore|Oracle\.ManagedDataAccess'
    'Snowflake'        = 'Snowflake\.Data'
}

$ormPatterns = @{
    'Entity Framework Core' = 'Microsoft\.EntityFrameworkCore'
    'Dapper'                = '^Dapper$|^Dapper\.'
    'ADO.NET (SqlClient)'   = 'System\.Data\.SqlClient|Microsoft\.Data\.SqlClient'
    'ADO.NET (Npgsql)'      = '^Npgsql$'
    'ADO.NET (MySql)'       = '^MySql\.Data$|^MySqlConnector$'
    'ADO.NET (SQLite)'      = 'System\.Data\.SQLite|Microsoft\.Data\.Sqlite'
    'ADO.NET (Oracle)'      = 'Oracle\.ManagedDataAccess'
    'RepoDB'                = '^RepoDb'
    'Linq2db'               = '^linq2db'
}

$allPackages = @()
foreach ($csproj in $csprojFiles) {
    [xml]$xml = Get-Content $csproj.FullName -Raw
    $pkgRefs = $xml.Project.ItemGroup.PackageReference | Where-Object { $_.Include }
    foreach ($pkg in $pkgRefs) { $allPackages += $pkg.Include }
}

# Database providers
$detectedDb = @()
foreach ($db in $dbPackagePatterns.Keys) {
    $pattern = $dbPackagePatterns[$db]
    if ($allPackages | Where-Object { $_ -match $pattern }) { $detectedDb += $db }
}

# ORM / data access
$detectedOrm = @()
foreach ($orm in $ormPatterns.Keys) {
    $pattern = $ormPatterns[$orm]
    if ($allPackages | Where-Object { $_ -match $pattern }) { $detectedOrm += $orm }
}

Write-Output "| Category | Detected |"
Write-Output "|---|---|"
Write-Output "| **Database Engine(s)** | $(if ($detectedDb.Count -gt 0) { $detectedDb -join ', ' } else { '_None detected_' }) |"
Write-Output "| **ORM / Data Access** | $(if ($detectedOrm.Count -gt 0) { $detectedOrm -join ', ' } else { '_None detected_' }) |"
Write-Output ""

$hasEfCore = $allPackages | Where-Object { $_ -match 'Microsoft\.EntityFrameworkCore' }

# Key variables
Write-Output "**Key Variables**:"
Write-Output "- ``DB_ENGINE`` = $(if ($detectedDb.Count -gt 0) { $detectedDb -join ', ' } else { 'NONE' })"
Write-Output "- ``DATA_ACCESS`` = $(if ($detectedOrm.Count -gt 0) { $detectedOrm -join ', ' } else { 'NONE' })"
Write-Output "- ``HAS_EFCORE`` = $(if ($hasEfCore) { 'true' } else { 'false' })"
Write-Output ""

# ═════════════════════════════════════════════
# 3. EF Core Details (if detected)
# ═════════════════════════════════════════════
if ($hasEfCore) {
    Write-Output "### EF Core Details"
    Write-Output ""

    # DbContext files
    $dbContextFiles = @()
    Get-ChildItem -Path $Root -Filter "*.cs" -Recurse -File |
        Where-Object { -not (Excluded $_.FullName) -and $_.FullName -notmatch '\\Migrations\\' } |
        ForEach-Object {
            $content = Get-Content $_.FullName -Raw
            if ($content -match ':\s*DbContext\b|:\s*IdentityDbContext') {
                $dbContextFiles += Rel $_.FullName
            }
        }

    if ($dbContextFiles.Count -gt 0) {
        Write-Output "**DbContext Files**:"
        foreach ($f in $dbContextFiles) { Write-Output "- ``$f``" }
        Write-Output ""
    }

    # Migration folders
    $migrationDirs = Get-ChildItem -Path $Root -Directory -Recurse |
        Where-Object { $_.Name -eq 'Migrations' -and -not (Excluded $_.FullName) }

    if ($migrationDirs) {
        Write-Output "**Migration Folders**:"
        foreach ($d in $migrationDirs) {
            $count = (Get-ChildItem $d.FullName -Filter "*.cs" -File).Count
            Write-Output "- ``$(Rel $d.FullName)/`` ($count files)"
        }
        Write-Output ""
    }

    # Entity/Model directories
    $modelDirs = Get-ChildItem -Path $Root -Directory -Recurse |
        Where-Object { $_.Name -match '^(Models|Entities|Domain)$' -and -not (Excluded $_.FullName) }

    if ($modelDirs) {
        Write-Output "**Entity/Model Directories**:"
        foreach ($d in $modelDirs) {
            $count = (Get-ChildItem $d.FullName -Filter "*.cs" -Recurse -File).Count
            Write-Output "- ``$(Rel $d.FullName)/`` ($count .cs files)"
        }
        Write-Output ""
    }
}

# ═════════════════════════════════════════════
# 4. Non-EF Data Access (if no EF Core)
# ═════════════════════════════════════════════
if (-not $hasEfCore) {
    Write-Output "### Non-EF Data Access Patterns"
    Write-Output ""

    $dataAccessFiles = @()
    Get-ChildItem -Path $Root -Filter "*.cs" -Recurse -File |
        Where-Object { -not (Excluded $_.FullName) } |
        ForEach-Object {
            $content = Get-Content $_.FullName -Raw
            $signals = @()
            if ($content -match 'SqlConnection|NpgsqlConnection|MySqlConnection|SqliteConnection|OracleConnection') { $signals += "DbConnection" }
            if ($content -match 'IDbConnection|IDbCommand') { $signals += "IDbConnection" }
            if ($content -match '\.QueryAsync|\.ExecuteAsync|\.QueryFirstAsync|\.QuerySingleAsync') { $signals += "Dapper" }
            if ($content -match 'SELECT\s|INSERT\s|UPDATE\s|DELETE\s|CREATE\s|ALTER\s') { $signals += "RawSQL" }
            if ($content -match 'SqlCommand|SqlDataReader|SqlDataAdapter') { $signals += "ADO.NET" }
            if ($signals.Count -gt 0) {
                $dataAccessFiles += [PSCustomObject]@{ File = Rel $_.FullName; Patterns = $signals -join ', ' }
            }
        }

    if ($dataAccessFiles.Count -gt 0) {
        Write-Output "| File | Patterns |"
        Write-Output "|---|---|"
        foreach ($f in $dataAccessFiles) { Write-Output "| ``$($f.File)`` | $($f.Patterns) |" }
        Write-Output ""
    } else {
        Write-Output "_No data access patterns detected in source files._"
        Write-Output ""
    }
}

# ═════════════════════════════════════════════
# 5. SQL Script Files
# ═════════════════════════════════════════════
Write-Output "### SQL Script Files"
Write-Output ""
$sqlFiles = Get-ChildItem -Path $Root -Include "*.sql" -Recurse -File | Where-Object { -not (Excluded $_.FullName) }
if ($sqlFiles) {
    Write-Output "| File | Lines |"
    Write-Output "|---|---|"
    foreach ($f in $sqlFiles) {
        $lines = (Get-Content $f.FullName | Measure-Object -Line).Lines
        Write-Output "| ``$(Rel $f.FullName)`` | $lines |"
    }
    Write-Output ""
} else {
    Write-Output "_None found._"
    Write-Output ""
}

# ═════════════════════════════════════════════
# 6. Connection Strings
# ═════════════════════════════════════════════
Write-Output "### Connection String Detection"
Write-Output ""
$configFiles = Get-ChildItem -Path $Root -Include "appsettings*.json","web.config","app.config" -Recurse -File |
    Where-Object { -not (Excluded $_.FullName) }

$connStringRows = @()
foreach ($cf in $configFiles) {
    $content = Get-Content $cf.FullName -Raw
    if ($content -match 'ConnectionString|connectionString|Data Source|Server=|Host=|Filename=') {
        $providers = @()
        if ($content -match 'Server=.*Database=|Data Source=.*Initial Catalog=|\.database\.windows\.net') { $providers += "SQL Server / Azure SQL" }
        if ($content -match 'Host=.*Port=.*Database=|postgresql|postgres') { $providers += "PostgreSQL" }
        if ($content -match 'server=.*port=3306|mysql') { $providers += "MySQL / MariaDB" }
        if ($content -match 'Data Source=.*\.db|Data Source=.*\.sqlite|Filename=.*\.db') { $providers += "SQLite" }
        if ($content -match 'User Id=.*Data Source=.*oracle|OracleConnection') { $providers += "Oracle" }
        if ($content -match 'snowflake|account=.*\.snowflakecomputing\.com') { $providers += "Snowflake" }
        $providerStr = if ($providers.Count -gt 0) { $providers -join ', ' } else { "_Unknown_" }
        $connStringRows += [PSCustomObject]@{ File = Rel $cf.FullName; Provider = $providerStr }
    }
}

if ($connStringRows.Count -gt 0) {
    Write-Output "| Config File | Likely Provider |"
    Write-Output "|---|---|"
    foreach ($r in $connStringRows) { Write-Output "| ``$($r.File)`` | $($r.Provider) |" }
    Write-Output ""
} else {
    Write-Output "_No connection strings detected._"
    Write-Output ""
}

# ═════════════════════════════════════════════
# 7. Frontend Detection
# ═════════════════════════════════════════════
Write-Output "## 3. Frontend Detection"
Write-Output ""

$frontendSignals = @()

# Config files
$frontendConfigs = @(
    'package.json', 'tsconfig.json', 'angular.json', '.angular-cli.json',
    'vite.config.ts', 'vite.config.js', 'next.config.js', 'next.config.mjs',
    'nuxt.config.ts', 'nuxt.config.js', 'svelte.config.js',
    'webpack.config.js', 'webpack.config.ts',
    'tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js'
)

$foundConfigs = @()
foreach ($configName in $frontendConfigs) {
    $found = Get-ChildItem -Path $Root -Filter $configName -Recurse -File |
        Where-Object { -not (Excluded $_.FullName) } | Select-Object -First 1
    if ($found) {
        $frontendSignals += $configName
        $foundConfigs += [PSCustomObject]@{ Type = "Config"; Item = Rel $found.FullName }
    }
}

# Frontend directories
$frontendDirs = @('wwwroot', 'ClientApp', 'client', 'frontend', 'web', 'app', 'src/app', 'pages', 'components')
foreach ($dir in $frontendDirs) {
    $found = Get-ChildItem -Path $Root -Directory -Recurse |
        Where-Object { $_.Name -eq $dir -and -not (Excluded $_.FullName) } | Select-Object -First 1
    if ($found) {
        $frontendSignals += "dir:$dir"
        $foundConfigs += [PSCustomObject]@{ Type = "Directory"; Item = Rel $found.FullName }
    }
}

# Frontend file extensions
$frontendExtensions = @('*.tsx', '*.jsx', '*.vue', '*.svelte', '*.razor')
foreach ($ext in $frontendExtensions) {
    $count = (Get-ChildItem -Path $Root -Filter $ext -Recurse -File | Where-Object { -not (Excluded $_.FullName) }).Count
    if ($count -gt 0) {
        $frontendSignals += $ext
        $foundConfigs += [PSCustomObject]@{ Type = "Files"; Item = "$count ``$ext`` files" }
    }
}

if ($foundConfigs.Count -gt 0) {
    Write-Output "| Signal Type | Found |"
    Write-Output "|---|---|"
    foreach ($fc in $foundConfigs) { Write-Output "| $($fc.Type) | $($fc.Item) |" }
    Write-Output ""
}

# package.json analysis
$packageJson = Get-ChildItem -Path $Root -Filter "package.json" -Recurse -File |
    Where-Object { -not (Excluded $_.FullName) } | Select-Object -First 1

if ($packageJson) {
    Write-Output "#### ``package.json`` Analysis (``$(Rel $packageJson.FullName)``)"
    Write-Output ""

    $pjContent = Get-Content $packageJson.FullName -Raw | ConvertFrom-Json

    $fwDetection = @{
        'React'    = 'react';    'Next.js'   = 'next'
        'Angular'  = '@angular/core'; 'Vue' = 'vue'
        'Nuxt'     = 'nuxt';    'Svelte'    = 'svelte'; 'SvelteKit' = '@sveltejs/kit'
    }

    $deps = @{}
    if ($pjContent.dependencies) { $pjContent.dependencies.PSObject.Properties | ForEach-Object { $deps[$_.Name] = $_.Value } }
    if ($pjContent.devDependencies) { $pjContent.devDependencies.PSObject.Properties | ForEach-Object { $deps[$_.Name] = $_.Value } }

    $fwRows = @()
    foreach ($fw in $fwDetection.Keys) {
        $pkg = $fwDetection[$fw]
        if ($deps.ContainsKey($pkg)) { $fwRows += [PSCustomObject]@{ Category = "Framework"; Name = $fw; Package = $pkg; Version = $deps[$pkg] } }
    }

    $stateLibs = @('redux', '@reduxjs/toolkit', 'zustand', 'mobx', 'pinia', 'vuex', '@ngrx/store', 'recoil', 'jotai')
    foreach ($lib in $stateLibs) { if ($deps.ContainsKey($lib)) { $fwRows += [PSCustomObject]@{ Category = "State Mgmt"; Name = $lib; Package = $lib; Version = $deps[$lib] } } }

    $uiLibs = @('@mui/material', 'antd', '@ant-design/icons', 'bootstrap', 'react-bootstrap',
        '@chakra-ui/react', '@radix-ui/react-dialog', '@headlessui/react', 'primereact', 'primevue',
        '@angular/material', 'vuetify', 'quasar')
    foreach ($lib in $uiLibs) { if ($deps.ContainsKey($lib)) { $fwRows += [PSCustomObject]@{ Category = "UI Library"; Name = $lib; Package = $lib; Version = $deps[$lib] } } }

    $buildTools = @('vite', 'webpack', 'esbuild', 'parcel', 'turbo', '@angular/cli')
    foreach ($bt in $buildTools) { if ($deps.ContainsKey($bt)) { $fwRows += [PSCustomObject]@{ Category = "Build Tool"; Name = $bt; Package = $bt; Version = $deps[$bt] } } }

    $testFw = @('jest', 'vitest', '@testing-library/react', '@testing-library/angular',
        '@testing-library/vue', 'playwright', 'cypress', '@playwright/test')
    foreach ($t in $testFw) { if ($deps.ContainsKey($t)) { $fwRows += [PSCustomObject]@{ Category = "Test"; Name = $t; Package = $t; Version = $deps[$t] } } }

    if ($fwRows.Count -gt 0) {
        Write-Output "| Category | Name | Package | Version |"
        Write-Output "|---|---|---|---|"
        foreach ($r in $fwRows) { Write-Output "| $($r.Category) | **$($r.Name)** | ``$($r.Package)`` | $($r.Version) |" }
        Write-Output ""
    }
}

$hasFrontend = $frontendSignals.Count -gt 0
Write-Output "**``HAS_FRONTEND`` = $(if ($hasFrontend) { 'true' } else { 'false' })**"
Write-Output ""

# ═════════════════════════════════════════════
# 8. Test Projects
# ═════════════════════════════════════════════
Write-Output "## 4. Test Projects"
Write-Output ""

$testRows = @()
foreach ($csproj in $csprojFiles) {
    [xml]$xml = Get-Content $csproj.FullName -Raw
    $pkgRefs = $xml.Project.ItemGroup.PackageReference | Where-Object { $_.Include }
    $testFrameworks = $pkgRefs | Where-Object {
        $_.Include -match 'xunit|nunit|mstest|FluentAssertions|Moq|NSubstitute|Shouldly|Bogus|AutoFixture|coverlet'
    }
    if ($testFrameworks) {
        foreach ($tf in $testFrameworks) {
            $testRows += [PSCustomObject]@{ Project = Rel $csproj.FullName; Package = $tf.Include; Version = $tf.Version }
        }
    }
}

if ($testRows.Count -gt 0) {
    Write-Output "| Project | Package | Version |"
    Write-Output "|---|---|---|"
    foreach ($r in $testRows) { Write-Output "| ``$($r.Project)`` | ``$($r.Package)`` | $($r.Version) |" }
    Write-Output ""
} else {
    Write-Output "_No test projects detected._"
    Write-Output ""
}

# ═════════════════════════════════════════════
# 9. CI/CD & DevOps
# ═════════════════════════════════════════════
Write-Output "## 5. CI/CD & DevOps"
Write-Output ""

$ciPatterns = @(
    '*.yml', '*.yaml', 'Jenkinsfile', '.gitlab-ci.yml',
    'Dockerfile', 'docker-compose.yml', 'docker-compose.yaml', '.dockerignore'
)
$ciFiles = @()
foreach ($pattern in $ciPatterns) {
    Get-ChildItem -Path $Root -Filter $pattern -Recurse -File |
        Where-Object { -not (Excluded $_.FullName) -and ($_.FullName -match '(workflows|pipelines|\.github|azure-pipelines|Dockerfile|docker-compose|Jenkinsfile|\.gitlab-ci|\.dockerignore)') } |
        ForEach-Object { $ciFiles += Rel $_.FullName }
}

# Also check root-level pipeline files
foreach ($name in @('azure-pipelines.yml', 'azure-pipelines.yaml', 'Jenkinsfile', '.gitlab-ci.yml', 'Dockerfile', 'docker-compose.yml', 'docker-compose.yaml', '.dockerignore')) {
    $rootFile = Join-Path $Root $name
    if (Test-Path $rootFile) {
        $relPath = Rel $rootFile
        if ($relPath -notin $ciFiles) { $ciFiles += $relPath }
    }
}

if ($ciFiles.Count -gt 0) {
    foreach ($f in $ciFiles) { Write-Output "- ``$f``" }
    Write-Output ""
} else {
    Write-Output "_No CI/CD or DevOps files detected._"
    Write-Output ""
}

# ═════════════════════════════════════════════
# 10. Entry Points
# ═════════════════════════════════════════════
Write-Output "## 6. Entry Points"
Write-Output ""

$entryPoints = @()
Get-ChildItem -Path $Root -Filter "Program.cs" -Recurse -File |
    Where-Object { -not (Excluded $_.FullName) } |
    ForEach-Object { $entryPoints += Rel $_.FullName }
Get-ChildItem -Path $Root -Filter "Startup.cs" -Recurse -File |
    Where-Object { -not (Excluded $_.FullName) } |
    ForEach-Object { $entryPoints += Rel $_.FullName }

if ($entryPoints.Count -gt 0) {
    foreach ($ep in $entryPoints) { Write-Output "- ``$ep``" }
    Write-Output ""
} else {
    Write-Output "_No entry points found._"
    Write-Output ""
}

# ═════════════════════════════════════════════
# 11. Configuration Files
# ═════════════════════════════════════════════
Write-Output "## 7. Configuration Files"
Write-Output ""

$configPatterns = @('appsettings*.json', 'web.config', 'app.config', 'launchSettings.json', '.env', '.env.*')
$configList = @()
foreach ($pattern in $configPatterns) {
    Get-ChildItem -Path $Root -Filter $pattern -Recurse -File |
        Where-Object { -not (Excluded $_.FullName) } |
        ForEach-Object { $configList += Rel $_.FullName }
}

if ($configList.Count -gt 0) {
    foreach ($c in $configList) { Write-Output "- ``$c``" }
    Write-Output ""
} else {
    Write-Output "_No configuration files found._"
    Write-Output ""
}

# ═════════════════════════════════════════════
# 12. Directory Tree
# ═════════════════════════════════════════════
Write-Output "## 8. Directory Tree"
Write-Output ""
Write-Output '```'

function Get-Tree([string]$Path, [int]$Depth, [int]$MaxDepth, [string]$Prefix = '') {
    if ($Depth -ge $MaxDepth) { return }
    $items = Get-ChildItem -Path $Path |
        Where-Object { $_.Name -notmatch '^(bin|obj|node_modules|\.git|\.vs|packages|TestResults|\.idea)$' } |
        Sort-Object { -not $_.PSIsContainer }, Name

    for ($i = 0; $i -lt $items.Count; $i++) {
        $item = $items[$i]
        $isLast = ($i -eq $items.Count - 1)
        $connector = if ($isLast) { '└── ' } else { '├── ' }
        $childPrefix = if ($isLast) { '    ' } else { '│   ' }

        if ($item.PSIsContainer) {
            Write-Output "$Prefix$connector$($item.Name)/"
            Get-Tree $item.FullName ($Depth + 1) $MaxDepth "$Prefix$childPrefix"
        } else {
            Write-Output "$Prefix$connector$($item.Name)"
        }
    }
}

Get-Tree $Root 0 4
Write-Output '```'
Write-Output ""

# ═════════════════════════════════════════════
# 13. Code Convention Signals
# ═════════════════════════════════════════════
Write-Output "## 9. Code Convention Signals"
Write-Output ""

$sampleFiles = Get-ChildItem -Path $Root -Filter "*.cs" -Recurse -File |
    Where-Object { -not (Excluded $_.FullName) -and $_.FullName -notmatch '\\(Migrations|AssemblyInfo)\\' } |
    Select-Object -First 10

$signals = [ordered]@{
    'file-scoped-namespace'  = 0
    'block-scoped-namespace' = 0
    'nullable-enable'        = 0
    'record-types'           = 0
    'primary-constructors'   = 0
    'collection-expressions' = 0
    'global-using'           = 0
    'async-await'            = 0
    'init-properties'        = 0
}

foreach ($f in $sampleFiles) {
    $content = Get-Content $f.FullName -Raw
    if ($content -match 'namespace\s+\S+;')           { $signals['file-scoped-namespace']++ }
    if ($content -match 'namespace\s+\S+\s*\{')       { $signals['block-scoped-namespace']++ }
    if ($content -match '#nullable\s+enable|<Nullable>enable') { $signals['nullable-enable']++ }
    if ($content -match '\brecord\b\s+(class|struct)?\s*\w+')  { $signals['record-types']++ }
    if ($content -match 'class\s+\w+\s*\(')           { $signals['primary-constructors']++ }
    if ($content -match '=\s*\[\s*\]')                 { $signals['collection-expressions']++ }
    if ($content -match '^global\s+using')             { $signals['global-using']++ }
    if ($content -match '\basync\b.*\bawait\b|\bawait\b') { $signals['async-await']++ }
    if ($content -match '\{\s*get;\s*init;\s*\}')      { $signals['init-properties']++ }
}

Write-Output "> Sampled **$($sampleFiles.Count)** ``.cs`` files"
Write-Output ""
Write-Output "| Convention | Files Using | Sampled |"
Write-Output "|---|---|---|"
foreach ($key in $signals.Keys) {
    $count = $signals[$key]
    $status = if ($count -gt 0) { "**$count**" } else { "0" }
    Write-Output "| ``$key`` | $status | $($sampleFiles.Count) |"
}
Write-Output ""

# ═════════════════════════════════════════════
# Summary
# ═════════════════════════════════════════════
Write-Output "## Summary"
Write-Output ""
Write-Output "| Variable | Value |"
Write-Output "|---|---|"
Write-Output "| ``DB_ENGINE`` | $(if ($detectedDb.Count -gt 0) { $detectedDb -join ', ' } else { 'NONE' }) |"
Write-Output "| ``DATA_ACCESS`` | $(if ($detectedOrm.Count -gt 0) { $detectedOrm -join ', ' } else { 'NONE' }) |"
Write-Output "| ``HAS_EFCORE`` | $(if ($hasEfCore) { 'true' } else { 'false' }) |"
Write-Output "| ``HAS_FRONTEND`` | $(if ($hasFrontend) { 'true' } else { 'false' }) |"
Write-Output "| ``.NET Projects`` | $($csprojFiles.Count) |"
Write-Output "| ``Test Projects`` | $(if ($testRows.Count -gt 0) { ($testRows | Select-Object -Property Project -Unique).Count } else { '0' }) |"
Write-Output "| ``SQL Scripts`` | $(if ($sqlFiles) { $sqlFiles.Count } else { '0' }) |"
Write-Output ""
Write-Output "---"
Write-Output ""
Write-Output "*The AI agent should now **read specific files** listed above for deeper analysis.*"
